spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost/tasks"
    username: "user"
    password: "12345"
